- name: Create User
  hosts: all
  become: true
  vars_prompt:
    - name: "username"
      prompt: "Enter user name"
      private: "no"

  tasks:
    - name: Create User using an existing home directory
      user:
        name: "{{ username }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: developers
        home: "/home/developers"
        create_home: yes
