- name: Rename specific VPN file
  hosts: web
  become: true

  vars:
    ccd_dir: /etc/openvpn/server/edev/ccd

  vars_prompt:
    - name: "username"
      prompt: "Enter the file name"
      private: no

  tasks:
    - name: check if the file is exist
      ansible.builtin.stat:
        path: "{{ccd_dir}}/{{username}}-BLOCK"
      register: vpn_file

    - name: Rename the file only if it exists
      ansible.builtin.command: 
        cmd: mv "{{ ccd_dir }}/{{ username }}-BLOCK" "{{ ccd_dir }}/{{ username }}"
      when: vpn_file.stat.exists
