- name: Rename specific VPN file
  hosts: web
  become: true

  vars:
    ccd_dir: /etc/openvpn/server/edev/ccd

  tasks:
    - name: check if the file exists
      ansible.builtin.stat:
        path: "{{ ccd_dir }}/{{ username }}-BLOCK"
      register: vpn_file

    - name: Rename the file only if it exists
      ansible.builtin.command:
        cmd: mv "{{ ccd_dir }}/{{ username }}-BLOCK" "{{ ccd_dir }}/{{ username }}"
      when: vpn_file.stat.exists
